### ISSUE TITLE
booter & requests not found

### ISSUE THREAD

**Issue by g36m3909** [CryonicsX/Gmail-Account-Creator#1]
Traceback (most recent call last):
  File "C:\Users\User\Downloads\project\main.py", line 1, in <module>
    from src.snippets import Booter, Reader, Proxy, Preview
  File "C:\Users\User\Downloads\project\src\snippets\__init__.py", line 3, in <module>
    from .proxy import *
  File "C:\Users\User\Downloads\project\src\snippets\proxy.py", line 1, in <module>
    import requests, threading
ModuleNotFoundError: No module named 'requests'

please someone help

**Comment by CryonicsX** [comment]
i'm selling new version @cryonicx telegram

**Comment by g36m3909** [comment]
messaged you

**Comment by g36m3909** [comment]
ok how can i contact you on telegram? can you send me your telegram link

**Comment by CryonicsX** [comment]
@cryonicx
